name: BlabberFish-venv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.3
  - torchaudio
  - librosa
  - ffmpeg
  - pip:
    - ffmpeg-python
    - openai-whisper
    - pyannote.audio
    - halo
